name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci
        working-directory: hello-world-project



      - name: Build Next.js Project
        run: npm run build
        working-directory: hello-world-project

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase App Hosting
        run: firebase apphosting:rollouts:create hello-world-backend --git-branch main --project studio-6652665935-1850d --force
        working-directory: hello-world-project
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}